import { StyleSheet } from "react-native";
import { FONT_SIZE, FONT_FAMILY, Colors } from "../../../../Constants";

export const HostListingFormStyles = StyleSheet.create({
  onBoardingContainer: {
    flex: 1,
    backgroundColor: Colors.whiteBgColor,
  },
  headerLabel: {
    fontSize: FONT_SIZE.lg,
    fontFamily: FONT_FAMILY.bold,
    color: Colors.black,
  },
  headerDescText: {
    fontSize: FONT_SIZE.xsl,
    fontFamily: FONT_FAMILY.medium,
    color: Colors.grayBottomTab,
  },
  hostInstructionContainer: {
    flex: 1,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderBottomWidth: 2,
    borderBottomColor: Colors.grayBorder,
    flexDirection: "row",
    alignItems: "center",
  },
  instructionCountContainer: {
    marginRight: 10,
    width: 20,
    height: 20,
    borderRadius: 20,
    backgroundColor: Colors.purpleLight,
    justifyContent: "center",
    alignItems: "center",
  },
  instructionCountText: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: FONT_SIZE.xs,
    color: Colors.white,
  },
  instructionHeaderLabel: {
    fontSize: FONT_SIZE.lmd,
    fontFamily: FONT_FAMILY.semiBold,
  },
  instructionText: {
    fontSize: FONT_SIZE.xsl,
    fontFamily: FONT_FAMILY.medium,
    color: Colors.grayBottomTab,
    marginTop: 3,
  },
  imageCont: {
    flex: 1,
    alignItems: "center",
  },
  image: {
    width: 90,
    height: 90,
  },
  floatingImageCont: {
    position: "absolute",
    top: "50%",
    left: "45%",
  },
  floatingImage: {
    width: 50,
    height: 50,
  },
  floatingImageContTwo: {
    position: "absolute",
    top: "60%",
    left: "20%",
    zIndex: 2,
  },
  floatingImageTwo: {
    width: 90,
    height: 40,
  },
  getStartedBtnCont: {
    padding: 15,
    justifyContent: "center",
    borderTopWidth: 1,
    borderTopColor: Colors.grayBorder
  },
  getStartedBtn: {
    marginHorizontal: 10,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.purpleLight,
    height: 45,
    borderRadius: 10,
  },
  getStartedText: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONT_FAMILY.medium,
    color: Colors.white,
  },
  headerNavCont: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 2,
    borderBottomColor: Colors.grayBorder,
  },
  typeOfPlaceCont: {
    flex: 1,
    backgroundColor: Colors.whiteBgColor,
  },
  paginationCont: {
    flexDirection: "row",
    alignItems: "center",
  },

  tabView: {
    width: 25,
    height: 4,
  },
  TOPHeaderText: {
    fontSize: FONT_SIZE.lg,
    fontFamily: FONT_FAMILY.bold,
    color: Colors.black,
  },
  TOPHeaderDescText: {
    fontSize: FONT_SIZE.xsl,
    fontFamily: FONT_FAMILY.medium,
    color: Colors.grayBottomTab,
    marginTop: 5,
  },
  TOPLabelText: {
    fontSize: FONT_SIZE.lmd,
    fontFamily: FONT_FAMILY.semiBold,
    color: Colors.black,
    marginBottom: 15,
  },
  placeCategoryCont: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    backgroundColor: "rgba(176, 176, 176, .3)",
    padding: 5,
    borderRadius: 20,
  },
  placeCategoryBtn: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  placeTypeContainer: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  placeOptionPressableBtn: {
    width: "45%",
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  roomCountContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: Colors.grayBorder,
  },
  TopTextStyle: {
    fontSize: FONT_SIZE.sm,
    color: Colors.black,
    fontFamily: FONT_FAMILY.regular,
  },
  roomCounterCont: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  roomCounterBtn: {
    width: 40,
    height: 40,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: Colors.grayBorder,
    justifyContent: "center",
    alignItems: "center",
  },
  counterText: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONT_FAMILY.medium,
    color: Colors.black,
    marginHorizontal: 10,
  },
  isItSharedCont: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  isItSharedText: {
    fontSize: FONT_SIZE.sm,
    color: Colors.black,
    fontFamily: FONT_FAMILY.regular,
  },
  buildingTypeCont: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 2,
    padding: 20,
    borderRadius: 15,
  },
  floorCountContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: Colors.grayBorder,
  },
  nextBtn: {
     alignSelf: "flex-end",
           width: 100,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.purpleLight,
    height: 45,
    borderRadius: 10,
  },
  amenitiesHeaderLabel: {
     flexDirection: "row",
                  alignItems: "center",
                  gap: 10,
                  marginBottom: 10,
  },
  amenitiesCategoryText: {
     fontSize: FONT_SIZE.md,
                    fontFamily: FONT_FAMILY.semiBold,
                    color: Colors.black,
  },
  seeMoreAmenitiesBtn: {
     height: 40,
                            borderWidth: 2,
                            borderRadius: 10,
                            borderColor: Colors.purpleLight,
                            marginTop: 10,
                            justifyContent: "center",
                            alignItems: "center",
  },
  amenitiesText: {
     flexDirection: "row",
                        alignItems: "center",
                        gap: 10,
  },
  seeMoreAmenitiesModal: {
   
                  flex: 1,
                  padding: 20,
                  backgroundColor: Colors.blackTransparent,
                  justifyContent: "flex-end",
                  alignItems: "center",
  },
  moreAmenitiesModalCont: {
     width: "100%",
                    backgroundColor: Colors.white,
                    padding: 15,
                    borderRadius: 20,
  },
  moreAmenitiesHeaderCont: {
      flexDirection: "row",
                        alignItems: "center",
                        justifyContent: "space-between",
  },
  moreAmenitiesHeaderText: {
     fontSize: FONT_SIZE.md,
                      fontFamily: FONT_FAMILY.medium,
  },
  closeMoreAmenitiesModalBtn: {
     justifyContent: "center",
                      alignItems: "center",
                      backgroundColor: Colors.grayBorder,
                      width: 24,
                      height: 24,
                      borderRadius: 24,
  }
});
