import { StyleSheet, Platform } from "react-native";
import { Colors, FONT_FAMILY, FONT_SIZE } from "../../../Constants";

export const FilterStyles = StyleSheet.create({
  filterScrollBody: {
    flexDirection: "row",
    alignItems: "center",

    backgroundColor: Colors.whiteBgColor,
    ...Platform.select({
      ios: {
        shadowColor: Colors.blackShadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  makeRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  backIcon: {
    width: 40,
    height: 40,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: Colors.grayBorder,
    justifyContent: "center",
    alignItems: "center",
  },
  stickyHeaderContainer: {
    flexDirection: "row",
    flex: 1,
    backgroundColor: Colors.whiteBgColor,
    borderBottomWidth: 2,
    borderBottomColor: Colors.grayBorder,
    paddingBottom: 5,
    paddingHorizontal: 15,
  },
  stickyHeaderText: {
    fontSize: FONT_SIZE.lg,
    fontFamily: FONT_FAMILY.semiBold,
    color: Colors.black,
    textAlign: "center",
  },
  filterText: {
    marginLeft: "35%",
    fontSize: FONT_SIZE.lg,
    fontFamily: FONT_FAMILY.semiBold,
    color: Colors.black,
  },
  propertyType: {
    padding: 8,
    borderWidth: 2,
    borderColor: Colors.grayBorder,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  propertyTypeText: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONT_FAMILY.regular,
    color: Colors.black,
  },
  headerLabelText: {
    fontSize: FONT_SIZE.lmd,
    fontFamily: FONT_FAMILY.semiBold,
    color: Colors.black,
    marginBottom: 15,
  },
  propertyTypeContainer: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  listingStatusContainer: {
    marginVertical: 20,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    backgroundColor: "rgba(176, 176, 176, .3)",
    padding: 5,
    borderRadius: 20,
  },
  listingStatusBox: {
    flex: 1,
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  listingStatusText: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONT_FAMILY.regular,
    color: Colors.black,
  },
  backNavBtn: {
    width: 45,
    height: 45,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: Colors.grayBorder,
    justifyContent: "center",
    alignItems: "center",
    marginRight: "30%",
  },
  locationPressableBox: {
    width: "100%",
    height: 50,
    backgroundColor: "white",
    borderRadius: 15,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 15,
    ...Platform.select({
      ios: {
        shadowColor: Colors.blackShadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  sortByOrderPressableBox: {
    width: "100%",
    height: 50,
    backgroundColor: "white",
    borderRadius: 15,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    paddingVertical: 10,
    paddingHorizontal: 15,
    ...Platform.select({
      ios: {
        shadowColor: Colors.blackShadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  filterBottomContentContainer: {
    borderTopWidth: 1,
    borderTopColor: Colors.grayBorder,
    gap: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 15,
  },
  resetBox: {
    height: 50,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderColor: Colors.grayBorder,
    borderWidth: 2,
    borderRadius: 40,
  },
  resetText: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONT_FAMILY.semiBold,
    color: Colors.black,
  },
  applyBox: {
    height: 50,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.purpleLight,
    borderRadius: 40,
  },
  applyText: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONT_FAMILY.semiBold,
    color: Colors.white,
  },
});
